// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"getting-started.mdx": () => import("../content/docs/getting-started.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "concepts/diff-engine.mdx": () => import("../content/docs/concepts/diff-engine.mdx?collection=docs"), "concepts/how-it-works.mdx": () => import("../content/docs/concepts/how-it-works.mdx?collection=docs"), "concepts/providers.mdx": () => import("../content/docs/concepts/providers.mdx?collection=docs"), "concepts/resource-identity.mdx": () => import("../content/docs/concepts/resource-identity.mdx?collection=docs"), "guides/ai-generation.mdx": () => import("../content/docs/guides/ai-generation.mdx?collection=docs"), "guides/campaign-variants.mdx": () => import("../content/docs/guides/campaign-variants.mdx?collection=docs"), "guides/google-ads-setup.mdx": () => import("../content/docs/guides/google-ads-setup.mdx?collection=docs"), "guides/google-display-campaigns.mdx": () => import("../content/docs/guides/google-display-campaigns.mdx?collection=docs"), "guides/google-other-campaigns.mdx": () => import("../content/docs/guides/google-other-campaigns.mdx?collection=docs"), "guides/google-pmax-campaigns.mdx": () => import("../content/docs/guides/google-pmax-campaigns.mdx?collection=docs"), "guides/google-search-campaigns.mdx": () => import("../content/docs/guides/google-search-campaigns.mdx?collection=docs"), "guides/google-shopping-campaigns.mdx": () => import("../content/docs/guides/google-shopping-campaigns.mdx?collection=docs"), "guides/meta-ads-setup.mdx": () => import("../content/docs/guides/meta-ads-setup.mdx?collection=docs"), "guides/meta-campaigns.mdx": () => import("../content/docs/guides/meta-campaigns.mdx?collection=docs"), "guides/shared-config.mdx": () => import("../content/docs/guides/shared-config.mdx?collection=docs"), "reference/api.mdx": () => import("../content/docs/reference/api.mdx?collection=docs"), "reference/bidding-strategies.mdx": () => import("../content/docs/reference/bidding-strategies.mdx?collection=docs"), "reference/cache.mdx": () => import("../content/docs/reference/cache.mdx?collection=docs"), "reference/cli.mdx": () => import("../content/docs/reference/cli.mdx?collection=docs"), "reference/configuration.mdx": () => import("../content/docs/reference/configuration.mdx?collection=docs"), "reference/extensions.mdx": () => import("../content/docs/reference/extensions.mdx?collection=docs"), "reference/targeting.mdx": () => import("../content/docs/reference/targeting.mdx?collection=docs"), }),
};
export default browserCollections;