// AI Variants feature page content

export const heroCode = `$ ads expand --campaign campaigns/brand-search.ts \\
    --locales de,fr,es \\
    --translate

  Expanding: brand-search → 3 locale variants

  ✓ campaigns/brand-search--de.ts    created  (DE · translated)
  ✓ campaigns/brand-search--fr.ts    created  (FR · translated)
  ✓ campaigns/brand-search--es.ts    created  (ES · translated)

  Each variant:
  · Campaign name suffixed with locale (e.g. "Arcflow — Brand Search — DE")
  · Headlines and descriptions translated by AI
  · geo() targeting updated to match locale
  · Budget and structure preserved from original

  Run \`ads plan\` to preview all changes before applying.`;

export const problemLines = [
  "Expanding to a new market means opening the platform UI and clicking through every campaign, ad group, and ad — duplicating and translating each one by hand.",
  "5 markets means 5x the campaigns to maintain. A budget change in the original campaign has to be repeated in every locale variant.",
  "Targeting a different audience angle — SaaS founders vs. ops managers — means yet another full duplication. The complexity compounds.",
  "ads-as-code expands a campaign into locale translations or ICP variants in one command. Variants are TypeScript files — diffable, reviewable, and applied like any other campaign.",
];

export const howSteps = [
  {
    title: "Locale translations — one campaign, every market",
    caption:
      "`ads expand --locales` creates translated copies of your campaign for each target locale. Headlines, descriptions, and body copy are translated by AI. Targeting and geo are updated automatically.",
    code: `$ ads expand --campaign campaigns/brand-search.ts \\
    --locales de,fr,es,nl,pt \\
    --translate

  Expanding brand-search → 5 locale variants...

  ─────────────────────────────────────────────────────────────────
  brand-search--de.ts  (German)
    ~ name          "Arcflow — Brand Search" → "Arcflow — Brand Search — DE"
    ~ geo           ["US"] → ["DE", "AT", "CH"]
    ~ headlines     15 headlines translated to German
    ~ descriptions  4 descriptions translated to German

  brand-search--fr.ts  (French)
    ~ name          "Arcflow — Brand Search" → "Arcflow — Brand Search — FR"
    ~ geo           ["US"] → ["FR", "BE", "CH"]
    ~ headlines     15 headlines translated to French
    ~ descriptions  4 descriptions translated to French

  … 3 more locales

  ✓ 5 files created. Run \`ads plan\` to review.`,
    lang: "shellscript" as const,
  },
  {
    title: "ICP expansion — same product, different audience angles",
    caption:
      "Use `ads expand --icps` to generate variants targeting different buyer personas. Each variant gets a new campaign name, rewritten copy for that persona, and adjusted keyword angles — while preserving budget and structure.",
    code: `$ ads expand --campaign campaigns/brand-search.ts \\
    --icps "ops managers at B2B SaaS,founders at early-stage startups,IT directors at mid-market companies" \\
    --rewrite-copy

  Expanding brand-search → 3 ICP variants...

  ─────────────────────────────────────────────────────────────────
  brand-search--ops-managers.ts
    ~ name       "Arcflow — Brand Search — Ops Managers"
    ~ headlines  Rewritten for: ops efficiency, team bandwidth, manual work elimination
    ~ Sample:    "Automate the Work Your Ops Team Hates"
                 "Reclaim 10 Hours a Week for Your Ops Team"
                 "No More Manual Handoffs — Arcflow Handles It"

  brand-search--founders.ts
    ~ name       "Arcflow — Brand Search — Founders"
    ~ headlines  Rewritten for: speed, scale, zero-code setup
    ~ Sample:    "Ship Workflows Without Engineering Help"
                 "Your Startup Needs This Before You Scale"
                 "One Person Can Run What Took a Team"

  brand-search--it-directors.ts
    ~ name       "Arcflow — Brand Search — IT Directors"
    ~ headlines  Rewritten for: security, compliance, enterprise integrations
    ~ Sample:    "Enterprise Workflow Automation, SOC 2 Ready"
                 "500+ Integrations, IT-Approved Security"

  ✓ 3 files created. Run \`ads plan\` to review.`,
    lang: "shellscript" as const,
  },
  {
    title: "Variant customization — fine-tune before applying",
    caption:
      "Variants are plain TypeScript files. Edit them like any campaign — adjust bids, swap headlines, change targeting. Then run `ads plan` to diff all variants at once.",
    code: `// campaigns/brand-search--de.ts
// Generated by \`ads expand\` — edit freely

import { google } from "@upspawn/ads/google";
import { keywords, exact, phrase } from "@upspawn/ads/helpers/keywords";
import { headlines, descriptions, rsa } from "@upspawn/ads/helpers/ads";
import { daily, eur } from "@upspawn/ads/helpers/budget";
import { geo, languages } from "@upspawn/ads/helpers/targeting";

export const arcflowBrandSearchDE = google.search({
  name: "Arcflow — Brand Search — DE",
  budget: daily(eur(30)),  // ← edit: adjust budget for DE market
  bidding: "maximize-clicks",
})
  .group("Core KW", (g) =>
    g
      .targeting(geo(["DE", "AT", "CH"]), languages(["de"]))
      .keywords(
        keywords(
          exact("arcflow"),
          exact("arcflow automatisierung"),
          phrase("workflow automatisierung"),
        )
      )
      .ad(
        rsa(
          headlines(
            "Workflows mit KI automatisieren",
            "Keine Code-Kenntnisse nötig",
            "500+ Integrationen, eine Plattform",
            "Arcflow: Alles läuft automatisch",
            "In Minuten deployen, nicht Monaten",
            // … 10 more translated headlines
          ),
          descriptions(
            "Arcflow verbindet Ihre Tools und automatisiert die Arbeit dazwischen. Kein Code. Sofort einsatzbereit.",
            "Über 500 Integrationen, KI-gesteuerte Logik und ein Trigger-System, das rund um die Uhr arbeitet.",
          )
        )
      )
  );`,
    lang: "typescript" as const,
  },
];

export const capabilities = [
  {
    title: "Locale translations",
    description:
      "`ads expand --locales` translates headlines, descriptions, and body copy into target languages and updates geo targeting to match.",
  },
  {
    title: "ICP expansion",
    description:
      "`ads expand --icps` rewrites copy for different buyer personas while preserving structure, budgets, and bidding strategy.",
  },
  {
    title: "Campaign multiplication",
    description:
      "One source campaign becomes N variant files. Every variant is a full TypeScript campaign definition — no templates, no magic.",
  },
  {
    title: "Customizable variants",
    description:
      "Variants are plain TypeScript files. Edit bids, copy, and targeting before applying. No lock-in to generated content.",
  },
  {
    title: "Batch generation",
    description:
      "Expand multiple campaigns in one pass. All variants are created, reviewed with `ads plan`, and applied in one `ads apply`.",
  },
  {
    title: "Preserves original structure",
    description:
      "Budget tiers, ad group hierarchy, keyword match types, and bidding strategy carry over unchanged from the source campaign.",
  },
];
