// Import feature page content

export const heroCode = `$ ads import

  Connecting to Google Ads (customer: 7300967494)...

  Importing campaigns...

  ✓  campaign/brand-search                  imported
  ✓  campaign/brand-search/core-keywords    imported
  ✓  campaign/brand-search/core-keywords/rsa imported
  ✓  campaign/competitor-targeting          imported
  ✓  campaign/retargeting                   imported
  ✓  campaign/retargeting/converters        imported
  ✓  campaign/retargeting/converters/rsa    imported
  ... 43 more resources

  50 campaigns · 127 ad groups · 384 keywords · 89 ads
  Written to campaigns/  — ready to modify.`;

export const problemLines = [
  "You have 50 campaigns built up over years — budgets tuned, keywords researched, audiences refined.",
  "Infrastructure-as-code sounds great. But you're not going to rewrite 50 campaigns from scratch.",
  "Import pulls your live account directly into TypeScript. No rewriting, no data entry, no starting over.",
  "Once it's in code, you own it: diff it, edit it, version it, apply changes with a plan.",
];

export const howSteps = [
  {
    title: "Import from Google Ads",
    caption:
      "Run `ads import` and your entire Google Ads account is pulled into TypeScript files. Campaigns, ad groups, keywords, ads, extensions — everything normalized into clean, idiomatic code.",
    code: `$ ads import

  Connecting to Google Ads...

  ✓  campaign/brand-search                  imported
  ✓  campaign/brand-search/core-keywords    imported
  ✓  campaign/competitor-targeting          imported
  ✓  campaign/retargeting                   imported
  ✓  campaign/retargeting/converters        imported

  50 campaigns · 127 ad groups · 384 keywords
  Written to campaigns/`,
    lang: "shellscript" as const,
  },
  {
    title: "Import from Meta",
    caption:
      "Same command, different provider. `ads import --provider meta` pulls your Meta campaigns into the same TypeScript format. One codebase, multiple platforms.",
    code: `$ ads import --provider meta

  Connecting to Meta Ads (account: act_123456789)...

  ✓  campaign/arcflow-awareness             imported
  ✓  campaign/arcflow-awareness/video-feed  imported
  ✓  campaign/arcflow-retarget              imported
  ✓  campaign/arcflow-retarget/converters   imported

  12 campaigns · 34 ad sets · 87 ads
  Written to campaigns/`,
    lang: "shellscript" as const,
  },
  {
    title: "Clean, editable TypeScript output",
    caption:
      "Imported campaigns become real TypeScript — not a JSON dump. Readable names, typed helpers, ready to modify. Change a budget, add a keyword, ship with `ads apply`.",
    code: `// campaigns/brand-search.ts (generated by ads import)
import { google } from "@upspawn/ads";
import { daily, usd } from "@upspawn/ads/helpers";

export const brandSearch = google.search({
  name: "Arcflow — Brand Search",
  budget: daily(usd(40)),
  bidding: "maximize-clicks",
})
  .group("Core Keywords", (g) =>
    g
      .keywords(["[arcflow]", "[arcflow app]", '"arcflow pricing"'])
      .ad(rsa(
        headlines(["Arcflow — AI Workflow Automation", "Automate Your Workflows", "Try Arcflow Free"]),
        descriptions(["Connect your tools and automate in minutes.", "No code required. Ship faster."]),
        url("https://arcflow.io"),
      ))
  );`,
    lang: "typescript" as const,
  },
];

export const capabilities = [
  {
    title: "Google Ads import",
    description:
      "Pull campaigns, ad groups, keywords, RSA ads, sitelinks, and callouts from your live Google Ads account.",
  },
  {
    title: "Meta Ads import",
    description:
      "Import Meta campaigns, ad sets, and ads with the same command and the same TypeScript output format.",
  },
  {
    title: "Clean code generation",
    description:
      "Imported campaigns become idiomatic TypeScript using the SDK's typed helpers — not raw JSON or unreadable blobs.",
  },
  {
    title: "Incremental import",
    description:
      "Already managing some campaigns in code? Import only the ones you haven't touched yet.",
  },
  {
    title: "Extensions included",
    description:
      "Sitelinks, callout extensions, and structured snippets are imported alongside your campaigns.",
  },
  {
    title: "Ready to modify",
    description:
      "Imported files are fully editable. Change anything and run `ads apply` to push the update.",
  },
];
